// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnfixmdhpkapdmehfmys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZml4bWRocGthcGRtZWhmbXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NDU5OTMsImV4cCI6MjA4NzAyMTk5M30.uOr-tMhlslTJqtAYiQPClyXW_p0K1KrUo3Cz6UwXbJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});